/* ============================================================
 *  bin2c.c — turn a binary file into a C source array.
 *
 *  Build-time tool (compiled with the host CC, runs on the build
 *  machine — NOT cross-compiled). Used to bake shell.elf into the
 *  host binary so a distributed host needs no external .elf file.
 *
 *  Usage:
 *      bin2c <input.bin> <symbol_name> <output.c>
 *
 *  Emits:
 *      #include <stddef.h>
 *      __attribute__((aligned(4)))
 *      const unsigned char <symbol>[] = { ... };
 *      const size_t <symbol>_len = N;
 *
 *  The 4-byte alignment is REQUIRED for XIP: the VM fetches RV32
 *  half-words straight from this array, so it must sit on at least
 *  a 2-byte boundary (loader rejects odd-addressed XIP code). 4 is
 *  a safe, simple over-alignment.
 *
 *  Portable C11: works under Linux, Cygwin, and mingw alike, so the
 *  build doesn't depend on xxd/python being installed.
 * ============================================================ */
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv) {
    if (argc != 4) {
        fprintf(stderr, "usage: %s <input.bin> <symbol> <output.c>\n",
                argv[0]);
        return 2;
    }
    const char *in_path  = argv[1];
    const char *symbol   = argv[2];
    const char *out_path = argv[3];

    FILE *in = fopen(in_path, "rb");
    if (!in) { fprintf(stderr, "bin2c: cannot open %s\n", in_path); return 1; }
    FILE *out = fopen(out_path, "wb");
    if (!out) { fprintf(stderr, "bin2c: cannot write %s\n", out_path);
                fclose(in); return 1; }

    fprintf(out,
        "/* Generated by bin2c from %s. Do not edit. */\n"
        "#include <stddef.h>\n\n"
        "__attribute__((aligned(4)))\n"
        "const unsigned char %s[] = {\n",
        in_path, symbol);

    size_t n = 0;
    int c;
    while ((c = fgetc(in)) != EOF) {
        if ((n % 16u) == 0u) fputs("    ", out);
        fprintf(out, "0x%02x,", (unsigned)(c & 0xff));
        n++;
        if ((n % 16u) == 0u) fputc('\n', out);
        else                 fputc(' ', out);
    }
    if ((n % 16u) != 0u) fputc('\n', out);

    fprintf(out,
        "};\n"
        "const size_t %s_len = %lu;\n",
        symbol, (unsigned long)n);

    fclose(in);
    fclose(out);

    if (n == 0) {
        fprintf(stderr, "bin2c: warning — %s was empty\n", in_path);
    }
    return 0;
}
