/* platform/rpi/main.c — microgarbage on bare-metal ARM (Pi Zero / raspi0).
 *
 * The first "first light" of the Raspberry Pi port: the RV32IMC VM
 * interpreter running on the ARM1176 CPU with NO operating system under
 * it, hosting a RISC-V guest ELF (embedded as a byte array — there is no
 * filesystem yet). Host output goes out via ARM semihosting, so it works
 * in QEMU (`-M raspi0 -semihosting`) with no UART/framebuffer bring-up.
 *
 * This is the desktop dev-kit's VM proven on the actual target CPU: a
 * RISC-V VM running on an ARM VM. The real hardware floor (GPIO/I2C,
 * mailbox framebuffer, PWM audio, the cache page table) layers in later
 * behind the same seams — see docs/rpi-port.md.
 *
 * Public domain (CC0). No warranty.
 */

#include "vm/vm_system.h"
#include "vm/vm_host_stdio.h"
#include "vm/vm_host_platform.h"
#include "vm/vm_host_hwio.h"

#include <stdio.h>
#include <stdint.h>

#include "guest_elf.h"   /* generated by build.sh: g_guest_elf[], g_guest_elf_len */

void     mmu_enable(void);      /* platform/rpi/mmu.c — flat identity map + L1 caches */
uint32_t mmu_read_sctlr(void);  /* CP15 c1, to prove MMU/caches engaged */
void     uart_init(void);       /* platform/rpi/uart.c — PL011; printf now goes here */

/* platform/rpi/fb.c — VideoCore mailbox framebuffer */
extern uint32_t fb_base, fb_size, fb_pitch, fb_w, fb_h, fb_bpp;
int      fb_request(uint32_t w, uint32_t h, uint32_t bpp);
void     fb_draw_bars(void);
uint32_t fb_pixel(uint32_t x, uint32_t y);
int      fb_dump_ppm(const char *filename);

/* VM storage — static, host-owned (the VM never mallocs). ~2 MB of BSS,
 * trivial on the Pi Zero's 512 MB. */
#define SHARED_BYTES (1024 * 1024)
#define LOCAL_BYTES  (1024 * 1024)
static uint8_t g_shared[SHARED_BYTES];
static uint8_t g_local[LOCAL_BYTES];

int main(void) {
    setvbuf(stdout, NULL, _IONBF, 0);   /* unbuffered → each write hits semihosting */

    mmu_enable();   /* MMU-on flat identity map so the L1 I/D caches work */
    uart_init();    /* PL011 up — everything below is real serial, not semihosting */

    uint32_t sctlr = mmu_read_sctlr();
    printf("== microgarbage on bare-metal ARM (raspi0 / arm1176) ==\n");
    printf("uart: PL011 @0x20201000 up (this text is real serial)\n");
    printf("mmu: identity map on  SCTLR=0x%08lx  M=%lu C=%lu I=%lu\n",
           (unsigned long)sctlr, (unsigned long)(sctlr & 1u),
           (unsigned long)((sctlr >> 2) & 1u), (unsigned long)((sctlr >> 12) & 1u));
    printf("host: RV32IMC interpreter, no OS.  guest: %u-byte ELF\n",
           (unsigned)g_guest_elf_len);

    VmSystem sys;
    VmSystemConfig cfg = {
        .shared_storage      = g_shared,
        .shared_storage_size = SHARED_BYTES,
        .local_storage       = g_local,
        .local_storage_size  = LOCAL_BYTES,
        .max_vms             = 1,
        .spawn_data_kb       = 16,
    };
    if (!vm_system_init(&sys, &cfg)) {
        printf("vm_system_init FAILED\n");
        return 1;
    }

    /* printf in the guest routes through SYS_FORMAT_AND_WRITE (platform),
     * so we don't need the raw-SYS_WRITE stdio module here. */
    VmHostPlatformConfig pc = {0};
    if (!vm_host_install_platform(&sys, &pc)     /* printf */
     || !vm_host_install_hwio(&sys)) {           /* GPIO -> real BCM2835 */
        printf("service install FAILED\n");
        return 1;
    }

    VmLoadVmResult lr = vm_system_load_vm(&sys, g_guest_elf, g_guest_elf_len,
                                          /*data_region=*/ 16384,
                                          VM_BACKING_COPY_RAM,
                                          VM_BACKING_COPY_RAM);
    if (lr.code != VM_SYS_OK) {
        printf("guest load FAILED (code=%d, load_result=%d)\n",
               lr.code, lr.load_result);
        return 1;
    }

    printf("--- guest output ---\n");
    bool done = vm_system_run(&sys, 100000000ull);
    printf("--- guest %s ---\n", done ? "halted cleanly" : "hit cycle cap");

    vm_system_destroy(&sys);

    /* ---- framebuffer: first pixels via the VideoCore mailbox ---- */
    printf("--- framebuffer (mailbox property interface) ---\n");
    if (fb_request(640, 480, 32) == 0) {
        printf("fb: %lux%lu x%lubpp  base=0x%08lx pitch=%lu size=%luKB\n",
               (unsigned long)fb_w, (unsigned long)fb_h, (unsigned long)fb_bpp,
               (unsigned long)fb_base, (unsigned long)fb_pitch,
               (unsigned long)(fb_size / 1024u));
        fb_draw_bars();
        uint32_t p0 = fb_pixel(2, 2);
        uint32_t p5 = fb_pixel(fb_w * 5u / 8u + 2u, 2);
        printf("fb: readback bar0=0x%06lx bar5=0x%06lx (expect ffffff, ff0000)\n",
               (unsigned long)(p0 & 0xFFFFFFu), (unsigned long)(p5 & 0xFFFFFFu));
        if (fb_dump_ppm("build/fb.ppm") == 0)
            printf("fb: wrote build/fb.ppm (color bars) via semihosting\n");
    } else {
        printf("fb: mailbox request FAILED\n");
    }

    printf("== a RISC-V guest ran on an ARM CPU. first light. ==\n");
    return 0;
}
