; ============================================================
;  siphon_probe.s — INTERACTIVE force-blank RENDERING-timing probe (DECOUPLED).
;
;  We've already established (dma_test / dma_rate_test) that the per-line GP-DMA
;  lands its bytes fine. The OPEN question is purely: does the per-scanline
;  force-blank ON -> DMA -> OFF cycle disturb THAT line's RENDERING on real
;  hardware? (Clean on ares/bsnes-plus, corrupts on real SNES: left-half of the
;  siphoned lines blanks / BG scrambles; the top no-siphon rows stay clean.
;  Hypothesis: force-blank halts the PPU next-line TILE FETCH ~dot 328, so
;  restoring too late leaves the next line stale. Latest-safe point ~dot 328.)
;
;  DECOUPLED design — the DMA can no longer touch the displayed image:
;    * The per-line GP-DMA writes to a WRAM scratch buffer via WMDATA ($2180),
;      NOT to VRAM. It consumes the same realistic bus time inside the force-blank
;      window but has ZERO visual effect. So anything we see is 100% the
;      force-blank rendering disturbance, never a mis-landed VRAM write.
;    * The displayed BG1 is a STATIC 4bpp DOG loaded once at init and NEVER
;      modified again. The H-IRQ does ZERO VRAM writes. The dog is the canvas we
;      watch: a line that renders cleanly through the force-blank cycle shows the
;      dog intact; a bad force-blank time blanks (black gap) or scrambles (broken
;      feature) that line. FLAT high-contrast colours make either obvious.
;
;  Canvas: a full-screen flat-colour cartoon dog, generated by tools/gen_probe_dog.c
;  into snes/gen/probe_dog.{chr,map,pal} (16-colour 4bpp, de-duplicated tiles).
;
;  Readout: on a SECOND layer (BG2), upper-right, priority over BG1 so the text
;  overlays the dog; BG2 colour 0 is transparent so only the glyphs show. BG2 sits
;  in the top no-H-IRQ band (rows 0..2) so a siphon-band force-blank never gaps it.
;
;  --- Live parameters (direct-page) ---
;    p_htime  9-bit dot (0..339) where the per-line IRQ fires (NO H-blank spin —
;             the op runs immediately at this dot). Default 300.
;    p_bytes  even GP-DMA byte count per line -> WRAM (2..64). Default 20.
;    p_mode   0 = DMA-only, no force-blank (now visually NULL — a control)
;             1 = FORCE-BLANK TOGGLE only ($8F, delay, $0F, no DMA)
;             2 = FORCE-BLANK + WRAM-DMA ($8F, MDMAEN, delay, $0F) — primary.
;             Default 2.
;    p_delay  extra CPU cycles (even, 0..64) burned between the DMA/blank and the
;             $0F restore ("restore rendering later" axis). Default 0.
;
;  --- Controls (edge-triggered, auto-joypad) ---
;    Left / Right : p_htime -1 / +1     (the hdot)
;    Up   / Down  : p_bytes +2 / -2     (the DMA width)
;    L / R        : p_delay +2 / -2
;    Select       : cycle p_mode 0->1->2->0
;    Start        : reset all params to defaults
;
;  --- Display ---
;    BG2 upper-right : readout  H=xxx B=xx M=x D=xx  (hex, live, over the dog).
;    Lines 0..23     : H-IRQ OFF — no-siphon reference (dog always clean here).
;    Lines 24..207   : SIPHON BAND — each line the H-IRQ runs the mode op with the
;                      live params (WRAM DMA + fb toggle, NO VRAM touch).
;    Sprites         : two rows of solid magenta 8x8 sprites in the band.
;
;  Build (from snes/), generator first:
;    gcc -O2 -o ../tools/gen_probe_dog ../tools/gen_probe_dog.c -lm
;    ../tools/gen_probe_dog gen                     ; -> gen/probe_dog.{chr,map,pal}
;    ca65 --cpu 65816 -o gen/siphon_probe.o siphon_probe.s
;    ld65 -C siphon_hblank_test.cfg -o gen/siphon_probe.sfc gen/siphon_probe.o
;  Produces a 65536-byte .sfc. The HW bug can't show on an emulator — the read is
;  the human's job on real hardware.
;  Public domain (CC0). No warranty.
; ============================================================
.p816
.include "snes.inc"

; ---- WRAM-port registers (not in snes.inc) ----
WMDATA  = $2180        ; WRAM data port (B-bus DMA target)
WMADDL  = $2181        ; WRAM address low
WMADDM  = $2182        ; WRAM address mid
WMADDH  = $2183        ; WRAM address high (bit0 = $7E/$7F bank)

; ---- VRAM word map ----
FONT_CHR_WORD = $0000  ; glyph/sprite CHR (BG2 char base 0, OBJ name base 0)
DOG_CHR_WORD  = $1000  ; dog CHR           (BG1 char base 1)
BG1_MAP_WORD  = $4000  ; dog tilemap       (BG1SC = $40)
BG2_MAP_WORD  = $4400  ; readout tilemap   (BG2SC = $44)

; ---- BG2 readout placement (upper-right, inside the top no-IRQ band) ----
RO_ROW  = 1
RO_COL  = 12           ; 19 glyphs -> cols 12..30
RO_CELL = BG2_MAP_WORD + RO_ROW*32 + RO_COL
; BG2 tile attribute: palette 1 (bit10) + priority (bit13) -> high byte $24. The
; readout uses CGRAM palette-1 colour 1 for the text; BG1 dog uses palette 0.
RO_ATTR = $24

; ---- geometry / timing ----
BAND_FIRST = 24        ; first siphon scanline (top 24 lines: H-IRQ OFF)
BAND_LINES = 184       ; lines 24..207

; WRAM scratch: $7E:8000 (clear of LowRAM/DP/stack at $7E:0000-$1FFF). Max fill =
; p_bytes(64) * BAND_LINES(184) = 11776 B -> stays in $7E:8000..$7E:AE00.
WRAM_ADDR_L = $00
WRAM_ADDR_M = $80
WRAM_ADDR_H = $00      ; bank bit 0 = 0 -> $7E

; font tile indices (uploaded to FONT_CHR_WORD)
T_H     = 16
T_M     = 17
T_EQ    = 18
T_BLANK = 19
OBJ_TILE = 20          ; solid sprite tile
; hex digit 0..F == tile index 0..F ; 'B'==$0B, 'D'==$0D reused as labels.

; ---- defaults ----
DEF_HTIME = 300
DEF_BYTES = 20
DEF_MODE  = 2
DEF_DELAY = 0

; ---- pad bit masks (16-bit auto-joypad, $4218/$4219) ----
;  hi byte: B Y Sel St Up Dn Lf Rt   lo byte: A X L R 0 0 0 0
PAD_RIGHT  = $0100
PAD_LEFT   = $0200
PAD_DOWN   = $0400
PAD_UP     = $0800
PAD_START  = $1000
PAD_SELECT = $2000
PAD_L      = $0020
PAD_R      = $0010

; ---- direct-page state ----
p_htime  = $00      ; 16-bit  live HTIME dot
p_bytes  = $02      ; 16-bit  live per-line byte count (even)
p_mode   = $04      ; 8-bit   0/1/2
p_delay  = $05      ; 8-bit   even 0..64
pad_cur  = $06      ; 16-bit  this frame's pad
pad_prev = $08      ; 16-bit  last frame's pad
pad_new  = $0A      ; 16-bit  newly-pressed edges (cur & ~prev)
line_rem = $0E      ; 8-bit   siphon scanlines left this frame
vline    = $0F      ; 8-bit   current siphon V line
ramvec   = $10      ; 16-bit  indirect IRQ dispatch (kernel-faithful)
jvec     = $12      ; 16-bit  computed NOP-sled jump target
jtmp     = $14      ; 16-bit  scratch

.segment "CODE"

; ============================================================
;  reset
; ============================================================
.proc reset_handler
    sei
    clc
    xce
    rep #$38
    .a16
    .i16
    ldx #$1FFF
    txs
    lda #$0000
    tcd                     ; DP = 0
    sep #$20
    .a8
    lda #$00
    pha
    plb                     ; DBR = 0

    ; indirect IRQ vector (mirror the kernel's jmp (ramvec) dispatch latency)
    lda #<siphon_isr
    sta ramvec
    lda #>siphon_isr
    sta ramvec+1

    lda #$80
    sta INIDISP             ; force-blank during setup

    ; --- static PPU config ---
    lda #$01
    sta BGMODE              ; mode 1 (BG1/BG2 4bpp, BG3 2bpp)
    lda #$13
    sta TM                  ; BG1 + BG2 + OBJ on main screen
    stz OBSEL               ; OBJ name base 0 -> OBJ tile 20 = font solid tile
    lda #$40
    sta BG1SC               ; BG1 tilemap base word $4000, 32x32
    lda #$44
    sta BG2SC               ; BG2 tilemap base word $4400, 32x32
    lda #$01
    sta BG12NBA             ; BG1 char base 1 ($1000), BG2 char base 0 ($0000)
    stz A1B0                ; DMA A-bus bank 0 (.loword sources)
    lda #$80
    sta VMAIN               ; VRAM word increment after high-byte write

    ; --- dog palette -> CGRAM 0 (16 colours) ---
    stz CGADD
    stz DMAP0
    lda #<CGDATA
    sta BBAD0
    rep #$20
    .a16
    lda #.loword(dog_pal)
    sta A1T0L
    lda #(16*2)
    sta DAS0L
    sep #$20
    .a8
    lda #$01
    sta MDMAEN

    ; --- BG2 text palette: CGRAM 17 (palette 1, colour 1) = white ---
    lda #17
    sta CGADD
    lda #$FF
    sta CGDATA
    lda #$7F
    sta CGDATA

    ; --- OBJ palette 0: color0 transparent, color1 magenta (CGRAM 128) ---
    lda #128
    sta CGADD
    stz DMAP0
    lda #<CGDATA
    sta BBAD0
    rep #$20
    .a16
    lda #.loword(obj_palette)
    sta A1T0L
    lda #(2*2)
    sta DAS0L
    sep #$20
    .a8
    lda #$01
    sta MDMAEN

    ; --- glyph/sprite CHR -> word 0 (21 tiles) ---
    rep #$20
    .a16
    lda #FONT_CHR_WORD
    sta VMADDL
    lda #.loword(chr_font)
    sta A1T0L
    lda #(21*32)
    sta DAS0L
    sep #$20
    .a8
    lda #$01
    sta DMAP0
    lda #<VMDATAL
    sta BBAD0
    lda #$01
    sta MDMAEN

    ; --- dog CHR (de-duplicated tiles) -> word $1000 ---
    rep #$20
    .a16
    lda #DOG_CHR_WORD
    sta VMADDL
    lda #.loword(dog_chr)
    sta A1T0L
    lda #(dog_chr_end - dog_chr)
    sta DAS0L
    sep #$20
    .a8
    lda #$01
    sta MDMAEN

    ; --- dog tilemap -> BG1 map word $4000 (32x32) ---
    rep #$20
    .a16
    lda #BG1_MAP_WORD
    sta VMADDL
    lda #.loword(dog_map)
    sta A1T0L
    lda #2048
    sta DAS0L
    sep #$20
    .a8
    lda #$01
    sta MDMAEN

    ; --- BG2 map -> fill transparent (blank tile) word $4400 (32x32) ---
    rep #$20
    .a16
    lda #BG2_MAP_WORD
    sta VMADDL
    lda #.loword(bg2_blank)
    sta A1T0L
    lda #2048
    sta DAS0L
    sep #$20
    .a8
    lda #$09                ; 2 regs + FIXED A-bus source (fill)
    sta DMAP0
    lda #<VMDATAL
    sta BBAD0
    lda #$01
    sta MDMAEN

    ; --- OAM -> sprites ---
    stz OAMADDL
    stz OAMADDH
    stz DMAP0
    lda #<OAMDATA
    sta BBAD0
    rep #$20
    .a16
    lda #.loword(oam_data)
    sta A1T0L
    lda #(512+32)
    sta DAS0L
    sep #$20
    .a8
    lda #$01
    sta MDMAEN

    ; --- live params = defaults, pad history clear ---
    jsr load_defaults
    rep #$20
    .a16
    stz pad_prev
    stz pad_cur
    sep #$20
    .a8

    ; --- draw the first readout, seed the first band ---
    jsr draw_readout
    jsr seed_band

    lda #$0F
    sta INIDISP             ; unblank
    lda #$B1
    sta NMITIMEN            ; NMI + V-IRQ + H-IRQ + auto-joypad read
    cli
@idle:
    wai
    bra @idle
.endproc

; ============================================================
;  load_defaults — reset all live params.
; ============================================================
.proc load_defaults
    php
    rep #$20
    .a16
    lda #DEF_HTIME
    sta p_htime
    lda #DEF_BYTES
    sta p_bytes
    sep #$20
    .a8
    lda #DEF_MODE
    sta p_mode
    lda #DEF_DELAY
    sta p_delay
    plp
    rts
.endproc

; ============================================================
;  seed_band — (re)prime the per-line WRAM siphon for a fresh frame. WRAM is
;  always CPU-accessible, but we still reset WMADD to $7E:8000 ONCE PER FRAME here
;  (mirrors the "set VMADD once before the band" pattern) so the fill pointer never
;  overflows. Sets up DMA channel 0 for A->WMDATA, arms HTIME=p_htime / VTIME=
;  BAND_FIRST, installs siphon_isr. A8 in/out.
; ============================================================
.proc seed_band
    .a8
    ; DMA ch0: mode 0 (1 reg, 1 byte, A increments) -> WMDATA ($2180)
    stz DMAP0               ; transfer mode 0, A->B
    lda #$80
    sta BBAD0               ; B-bus = $2180 (WMDATA)
    stz A1B0                ; source bank 0 (ROM blob, content discarded)
    ; reset the WRAM fill pointer to $7E:8000
    lda #WRAM_ADDR_L
    sta WMADDL
    lda #WRAM_ADDR_M
    sta WMADDM
    lda #WRAM_ADDR_H
    sta WMADDH
    ; scanline bookkeeping
    lda #BAND_LINES
    sta line_rem
    lda #BAND_FIRST
    sta vline
    ; arm the timer: H = live HTIME, V = first band line (>= 24)
    lda p_htime
    sta HTIMEL
    lda p_htime+1
    sta HTIMEH              ; only bit0 (=dot bit8) is significant
    lda #BAND_FIRST
    sta VTIMEL
    stz VTIMEH
    ; install the lean per-line siphon handler
    lda #<siphon_isr
    sta ramvec
    lda #>siphon_isr
    sta ramvec+1
    rts
.endproc

; ============================================================
;  siphon_isr — LEAN per-scanline handler (installed in ramvec). Fires at
;  V=vline, H=p_htime. Does ONLY: [force-blank ON] -> [WRAM DMA] -> [burn delay] ->
;  [force-blank OFF]. ZERO VRAM writes. Mirrors the real kernel's siphon_isr shape
;  / dispatch latency. NO register save (idle loop is scratch).
; ============================================================
.proc siphon_isr
    sep #$30                ; force A8/I8 (idle loop left width unknown)
    .a8
    .i8
    lda TIMEUP              ; ack H/V-timer IRQ ($4211)
    lda line_rem
    bne @go
    jmp sip_stop            ; band exhausted — leave display unblanked
@go:
    ; per line: A1T0L = dma_blob (fixed ROM, discarded), DAS0L = p_bytes.
    ; WMADD auto-advances across the band, so the WRAM writes stream forward.
    rep #$20
    .a16
    lda #.loword(dma_blob)
    sta A1T0L
    lda p_bytes
    and #$00FF
    sta DAS0L
    sep #$20
    .a8
    ; --- mode dispatch (fire the operation AT p_htime, no H-blank spin) ---
    lda p_mode
    bne @m12
    ; mode 0: WRAM DMA only, never touch INIDISP -> visually NULL control.
    lda #$01
    sta MDMAEN
    jmp sip_adv
@m12:
    cmp #1
    beq @m1
    ; mode 2: force-blank + WRAM DMA + delay + unblank (the primary case)
    lda #$8F
    sta INIDISP
    lda #$01
    sta MDMAEN
    jmp @burn
@m1:
    ; mode 1: force-blank + delay + unblank, NO DMA (pure fb-toggle)
    lda #$8F
    sta INIDISP
    ; fall through to @burn
@burn:
    ; burn exactly p_delay CPU cycles (even, 0..64) via a NOP sled. Each NOP = 1
    ; byte / 2 cycles; jump into the sled at (end - p_delay/2 NOPs). The fixed
    ; setup below is constant for all p_delay, so only p_delay varies the
    ; blank->restore gap.
    rep #$20
    .a16
    lda p_delay
    and #$00FF
    lsr a                   ; NOP count = p_delay/2
    sta jtmp
    lda #.loword(nop_sled_end)
    sec
    sbc jtmp
    sta jvec
    sep #$20
    .a8
    jmp (jvec)
nop_sled:
    .repeat 32
        nop
    .endrepeat
nop_sled_end:
    lda #$0F
    sta INIDISP             ; restore rendering
    ; fall into sip_adv
sip_adv:
    ; dec line counter, re-arm V for the next scanline (H persists at p_htime)
    dec line_rem
    beq sip_stop
    inc vline
    lda vline
    sta VTIMEL
    stz VTIMEH
    rti
sip_stop:
    lda #$0F
    sta INIDISP             ; ensure display restored after the band
    rti
.endproc

; ============================================================
;  nmi_handler — vblank: read pad, apply edge-triggered controls, redraw the
;  readout, and re-seed the band for the next frame.
; ============================================================
.proc nmi_handler
    rep #$30
    .a16
    .i16
    pha
    phx
    phy
    sep #$20
    .a8
    lda RDNMI               ; ack NMI
    ; auto-joypad read may still be running at NMI entry — wait for it
@jw:
    lda HVBJOY
    and #$01
    bne @jw
    rep #$20
    .a16
    lda JOY1L               ; 16-bit read of $4218/$4219
    sta pad_cur
    ; edges: new = cur & ~prev
    lda pad_prev
    eor #$FFFF
    and pad_cur
    sta pad_new

    ; ---- HTIME (Left/Right), BYTES (Up/Down) : 16-bit vars ----
    lda pad_new
    and #PAD_LEFT
    beq @noL
    lda p_htime
    beq @noL                ; clamp low at 0
    dec a
    sta p_htime
@noL:
    lda pad_new
    and #PAD_RIGHT
    beq @noR
    lda p_htime
    cmp #339
    bcs @noR                ; clamp high at 339
    inc a
    sta p_htime
@noR:
    lda pad_new
    and #PAD_UP
    beq @noU
    lda p_bytes
    cmp #64
    bcs @noU                ; clamp high at 64
    inc a
    inc a
    sta p_bytes
@noU:
    lda pad_new
    and #PAD_DOWN
    beq @noD
    lda p_bytes
    cmp #4
    bcc @noD                ; clamp low at 2 (need >=4 to sub 2)
    dec a
    dec a
    sta p_bytes
@noD:

    ; ---- DELAY (L/R shoulders), MODE (Select), reset (Start) : 8-bit ----
    sep #$20
    .a8
    lda pad_new             ; low byte = A X L R ....
    and #PAD_L
    beq @noLs
    lda p_delay
    cmp #64
    bcs @noLs               ; clamp high at 64
    inc a
    inc a
    sta p_delay
@noLs:
    lda pad_new
    and #PAD_R
    beq @noRs
    lda p_delay
    cmp #2
    bcc @noRs               ; clamp low at 0 (need >=2 to sub 2)
    dec a
    dec a
    sta p_delay
@noRs:
    lda pad_new+1           ; high byte = B Y Sel St Up Dn Lf Rt
    and #(PAD_SELECT >> 8)  ; Select
    beq @noSel
    lda p_mode
    inc a
    cmp #3
    bcc @modeok
    lda #0
@modeok:
    sta p_mode
@noSel:
    lda pad_new+1
    and #(PAD_START >> 8)   ; Start
    beq @noStart
    jsr load_defaults
@noStart:

    ; ---- save pad history ----
    rep #$20
    .a16
    lda pad_cur
    sta pad_prev
    sep #$20
    .a8

    ; ---- redraw readout (BG2, upper-right) ----
    jsr draw_readout

    ; ---- re-seed the band for next frame ----
    jsr seed_band

    rep #$30
    .a16
    .i16
    ply
    plx
    pla
    rti
.endproc

; ============================================================
;  draw_readout — write the live params as hex into BG2 (upper-right). Layout:
;    H = h h h _ B = b b _ M = m _ D = d d
;  ('B','D' labels reuse hex-digit tiles $0B/$0D). Direct VMDATA writes in vblank
;  to the BG2 tilemap only (never BG1 / the dog canvas). A8 in/out.
; ============================================================
.proc draw_readout
    .a8
    lda #$80
    sta VMAIN               ; word increment
    rep #$20
    .a16
    lda #RO_CELL
    sta VMADDL
    sep #$20
    .a8
    ; label "H="
    lda #T_H
    jsr emit_tile
    lda #T_EQ
    jsr emit_tile
    ; HTIME (3 hex digits; value <= $153 so mid/low nibbles live in the low byte)
    lda p_htime+1
    and #$0F
    jsr emit_tile           ; digit 2
    lda p_htime
    lsr a
    lsr a
    lsr a
    lsr a
    and #$0F
    jsr emit_tile           ; digit 1
    lda p_htime
    and #$0F
    jsr emit_tile           ; digit 0
    lda #T_BLANK
    jsr emit_tile
    ; label "B="
    lda #$0B                ; 'B' glyph (hex-digit B)
    jsr emit_tile
    lda #T_EQ
    jsr emit_tile
    ; BYTES (2 hex digits)
    lda p_bytes
    lsr a
    lsr a
    lsr a
    lsr a
    and #$0F
    jsr emit_tile
    lda p_bytes
    and #$0F
    jsr emit_tile
    lda #T_BLANK
    jsr emit_tile
    ; label "M="
    lda #T_M
    jsr emit_tile
    lda #T_EQ
    jsr emit_tile
    ; MODE (1 hex digit)
    lda p_mode
    and #$0F
    jsr emit_tile
    lda #T_BLANK
    jsr emit_tile
    ; label "D="
    lda #$0D                ; 'D' glyph (hex-digit D)
    jsr emit_tile
    lda #T_EQ
    jsr emit_tile
    ; DELAY (2 hex digits)
    lda p_delay
    lsr a
    lsr a
    lsr a
    lsr a
    and #$0F
    jsr emit_tile
    lda p_delay
    and #$0F
    jsr emit_tile
    rts
.endproc

; emit one BG2 tilemap word: tile in A (low byte), attribute = RO_ATTR (palette 1
; + priority). VMAIN=$80 -> the word address auto-increments after the high write.
.proc emit_tile
    .a8
    sta VMDATAL
    lda #RO_ATTR
    sta VMDATAH
    rts
.endproc

; ============================================================
;  IRQ trampoline (indirect, kernel-faithful) + NMI/stub
; ============================================================
.proc irq_tramp
    jmp (ramvec)
.endproc
.proc nmi_stub
    rti
.endproc

; ============================================================
;  Data
; ============================================================

; 1bpp glyph -> 4bpp tile: plane0 = the 8 row bytes (color index 1), planes 1..3 = 0.
.macro glyph b0,b1,b2,b3,b4,b5,b6,b7
    .byte b0,$00, b1,$00, b2,$00, b3,$00
    .byte b4,$00, b5,$00, b6,$00, b7,$00
    .res 16, $00
.endmacro

bg2_blank:
    .word T_BLANK          ; BG2 fill = transparent blank tile

; --- glyph/sprite font CHR (tiles 0..20) ---
chr_font:
    glyph $3C,$66,$6E,$76,$66,$66,$3C,$00   ; 0
    glyph $18,$38,$18,$18,$18,$18,$7E,$00   ; 1
    glyph $3C,$66,$06,$0C,$30,$60,$7E,$00   ; 2
    glyph $3C,$66,$06,$1C,$06,$66,$3C,$00   ; 3
    glyph $0C,$1C,$3C,$6C,$7E,$0C,$0C,$00   ; 4
    glyph $7E,$60,$7C,$06,$06,$66,$3C,$00   ; 5
    glyph $1C,$30,$60,$7C,$66,$66,$3C,$00   ; 6
    glyph $7E,$06,$0C,$18,$30,$30,$30,$00   ; 7
    glyph $3C,$66,$66,$3C,$66,$66,$3C,$00   ; 8
    glyph $3C,$66,$66,$3E,$06,$0C,$38,$00   ; 9
    glyph $18,$3C,$66,$66,$7E,$66,$66,$00   ; A
    glyph $7C,$66,$66,$7C,$66,$66,$7C,$00   ; B
    glyph $3C,$66,$60,$60,$60,$66,$3C,$00   ; C
    glyph $78,$6C,$66,$66,$66,$6C,$78,$00   ; D
    glyph $7E,$60,$60,$78,$60,$60,$7E,$00   ; E
    glyph $7E,$60,$60,$78,$60,$60,$60,$00   ; F
    glyph $66,$66,$66,$7E,$66,$66,$66,$00   ; 16 'H'
    glyph $63,$77,$7F,$6B,$63,$63,$63,$00   ; 17 'M'
    glyph $00,$00,$7E,$00,$7E,$00,$00,$00   ; 18 '='
    glyph $00,$00,$00,$00,$00,$00,$00,$00   ; 19 blank (transparent)
    glyph $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF   ; 20 solid (sprite)

; A 64-byte ROM blob the per-line WRAM DMA reads from (content discarded).
dma_blob:
    .res 64, $A5

; --- generated dog canvas (tools/gen_probe_dog.c) ---
dog_pal:
    .incbin "gen/probe_dog.pal"        ; 16 BGR555 words -> CGRAM 0
dog_map:
    .incbin "gen/probe_dog.map"        ; 32x32 tilemap (2048 B), BG1 base 1
dog_chr:
    .incbin "gen/probe_dog.chr"        ; N de-duplicated 4bpp tiles
dog_chr_end:

; --- OBJ palette 0: transparent + magenta ---
obj_palette:
    .word $0000
    .word $7C1F

; --- OAM: two rows of 8 solid sprites inside the band, rest hidden ---
.macro objrow SY
    .byte  16, SY, OBJ_TILE, $30
    .byte  48, SY, OBJ_TILE, $30
    .byte  80, SY, OBJ_TILE, $30
    .byte 112, SY, OBJ_TILE, $30
    .byte 144, SY, OBJ_TILE, $30
    .byte 176, SY, OBJ_TILE, $30
    .byte 208, SY, OBJ_TILE, $30
    .byte 232, SY, OBJ_TILE, $30
.endmacro
oam_data:
    objrow 96
    objrow 168
    .repeat (128-16)               ; hide the remaining sprites
        .byte 0, 240, 0, 0
    .endrepeat
    .repeat 32                     ; high table: 8x8, X-high 0
        .byte $00
    .endrepeat

; ============================================================
;  HiROM-shaped header + vectors (matches siphon_hblank_test.cfg)
; ============================================================
.segment "HEADER"
    .byte "SIPHON PROBE DOG     "   ; 21 chars
    .byte $31
    .byte $00
    .byte $07
    .byte $00
    .byte $01
    .byte $00
    .byte $00
    .word $AAAA
    .word $5555

.segment "VECTORS"
    .word $0000
    .word $0000
    .word $0000
    .word nmi_handler        ; native NMI
    .word $0000
    .word irq_tramp          ; native IRQ
    .word $0000
    .word $0000
    .word $0000
    .word $0000
    .word $0000
    .word nmi_stub           ; emulation NMI (unused after xce)
    .word reset_handler
    .word irq_tramp          ; emulation IRQ
